# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ny_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NyMedlem(object):
    def setupUi(self, NyMedlem):
        NyMedlem.setObjectName("NyMedlem")
        NyMedlem.resize(438, 563)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NyMedlem)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.namn_id = QtWidgets.QLabel(NyMedlem)
        self.namn_id.setObjectName("namn_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namn_id)
        self.namn = QtWidgets.QLineEdit(NyMedlem)
        self.namn.setObjectName("namn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.namn)
        self.grupp = QtWidgets.QLabel(NyMedlem)
        self.grupp.setObjectName("grupp")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.grupp)
        self.kommentar = QtWidgets.QLabel(NyMedlem)
        self.kommentar.setObjectName("kommentar")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.kommentar)
        self.group_val = QtWidgets.QComboBox(NyMedlem)
        self.group_val.setCurrentText("")
        self.group_val.setObjectName("group_val")
        self.group_val.addItem("")
        self.group_val.addItem("")
        self.group_val.addItem("")
        self.group_val.addItem("")
        self.group_val.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.group_val)
        self.ID_label = QtWidgets.QLabel(NyMedlem)
        self.ID_label.setObjectName("ID_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ID_label)
        self.ID_show = QtWidgets.QLabel(NyMedlem)
        self.ID_show.setObjectName("ID_show")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ID_show)
        self.Betalt = QtWidgets.QLabel(NyMedlem)
        self.Betalt.setObjectName("Betalt")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Betalt)
        self.radioButton = QtWidgets.QRadioButton(NyMedlem)
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.radioButton)
        self.textEdit = QtWidgets.QTextEdit(NyMedlem)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.adress = QtWidgets.QLabel(NyMedlem)
        self.adress.setObjectName("adress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.adress)
        self.lineEdit_2 = QtWidgets.QLineEdit(NyMedlem)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.postnum = QtWidgets.QLabel(NyMedlem)
        self.postnum.setObjectName("postnum")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.postnum)
        self.lineEdit_3 = QtWidgets.QLineEdit(NyMedlem)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pers_num = QtWidgets.QLabel(NyMedlem)
        self.pers_num.setObjectName("pers_num")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pers_num)
        self.lineEdit_4 = QtWidgets.QLineEdit(NyMedlem)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label = QtWidgets.QLabel(NyMedlem)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(NyMedlem)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(NyMedlem)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NyMedlem)
        self.group_val.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(NyMedlem.accept)
        self.buttonBox.rejected.connect(NyMedlem.reject)
        QtCore.QMetaObject.connectSlotsByName(NyMedlem)

    def retranslateUi(self, NyMedlem):
        _translate = QtCore.QCoreApplication.translate
        NyMedlem.setWindowTitle(_translate("NyMedlem", "NyMedlem"))
        self.namn_id.setText(_translate("NyMedlem", "Namn:"))
        self.namn.setPlaceholderText(_translate("NyMedlem", "Namn Efternamn"))
        self.grupp.setText(_translate("NyMedlem", "Grupp:"))
        self.kommentar.setText(_translate("NyMedlem", "Kommentar:"))
        self.group_val.setItemText(0, _translate("NyMedlem", "Basic"))
        self.group_val.setItemText(1, _translate("NyMedlem", "Intermidiate"))
        self.group_val.setItemText(2, _translate("NyMedlem", "Advanced"))
        self.group_val.setItemText(3, _translate("NyMedlem", "Kids"))
        self.group_val.setItemText(4, _translate("NyMedlem", "Tävling"))
        self.ID_label.setText(_translate("NyMedlem", "ID:"))
        self.ID_show.setText(_translate("NyMedlem", "None"))
        self.Betalt.setText(_translate("NyMedlem", "Betalt:"))
        self.radioButton.setText(_translate("NyMedlem", "Ja"))
        self.adress.setText(_translate("NyMedlem", "Adress:"))
        self.lineEdit_2.setPlaceholderText(_translate("NyMedlem", "Tellusgatan 15"))
        self.postnum.setText(_translate("NyMedlem", "Postnummer:"))
        self.lineEdit_3.setPlaceholderText(_translate("NyMedlem", "224 57"))
        self.pers_num.setText(_translate("NyMedlem", "Personnummer:"))
        self.lineEdit_4.setPlaceholderText(_translate("NyMedlem", "xxxxxx-xxxx"))
        self.label.setText(_translate("NyMedlem", "Ort:"))
        self.lineEdit.setPlaceholderText(_translate("NyMedlem", "Lund"))
