# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rf_entry.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RF_Entry(object):
    def setupUi(self, RF_Entry):
        RF_Entry.setObjectName("RF_Entry")
        RF_Entry.resize(1419, 1195)
        self.centralwidget = QtWidgets.QWidget(RF_Entry)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.reportWindow = QtWidgets.QTableWidget(self.centralwidget)
        self.reportWindow.setMinimumSize(QtCore.QSize(1391, 0))
        self.reportWindow.setMaximumSize(QtCore.QSize(1391, 16777215))
        self.reportWindow.setLineWidth(1)
        self.reportWindow.setAlternatingRowColors(True)
        self.reportWindow.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.reportWindow.setTextElideMode(QtCore.Qt.ElideLeft)
        self.reportWindow.setShowGrid(True)
        self.reportWindow.setObjectName("reportWindow")
        self.reportWindow.setColumnCount(3)
        self.reportWindow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.reportWindow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportWindow.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.reportWindow.setHorizontalHeaderItem(2, item)
        self.reportWindow.horizontalHeader().setStretchLastSection(True)
        self.reportWindow.verticalHeader().setVisible(True)
        self.reportWindow.verticalHeader().setHighlightSections(False)
        self.reportWindow.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.reportWindow, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setCheckable(True)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        RF_Entry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RF_Entry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1419, 27))
        self.menubar.setObjectName("menubar")
        self.menuMeny = QtWidgets.QMenu(self.menubar)
        self.menuMeny.setObjectName("menuMeny")
        RF_Entry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RF_Entry)
        self.statusbar.setObjectName("statusbar")
        RF_Entry.setStatusBar(self.statusbar)
        self.actionExport_CSV = QtWidgets.QAction(RF_Entry)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionSettings = QtWidgets.QAction(RF_Entry)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(RF_Entry)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMeny.addAction(self.actionExport_CSV)
        self.menuMeny.addAction(self.actionSettings)
        self.menuMeny.addSeparator()
        self.menuMeny.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMeny.menuAction())

        self.retranslateUi(RF_Entry)
        QtCore.QMetaObject.connectSlotsByName(RF_Entry)

    def retranslateUi(self, RF_Entry):
        _translate = QtCore.QCoreApplication.translate
        RF_Entry.setWindowTitle(_translate("RF_Entry", "RF Entry"))
        item = self.reportWindow.horizontalHeaderItem(0)
        item.setText(_translate("RF_Entry", "Grupp"))
        item = self.reportWindow.horizontalHeaderItem(1)
        item.setText(_translate("RF_Entry", "Betalt"))
        item = self.reportWindow.horizontalHeaderItem(2)
        item.setText(_translate("RF_Entry", "Namn"))
        self.startButton.setText(_translate("RF_Entry", "Start"))
        self.clearButton.setText(_translate("RF_Entry", "Clear Log"))
        self.menuMeny.setTitle(_translate("RF_Entry", "Meny"))
        self.actionExport_CSV.setText(_translate("RF_Entry", "Export CSV"))
        self.actionSettings.setText(_translate("RF_Entry", "Settings"))
        self.actionQuit.setText(_translate("RF_Entry", "Quit"))
