# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rf_entry.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RF_Entry(object):
    def setupUi(self, RF_Entry):
        RF_Entry.setObjectName("RF_Entry")
        RF_Entry.resize(1419, 1195)
        self.centralwidget = QtWidgets.QWidget(RF_Entry)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(1391, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(1391, 16777215))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        RF_Entry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RF_Entry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1419, 27))
        self.menubar.setObjectName("menubar")
        self.menuMeny = QtWidgets.QMenu(self.menubar)
        self.menuMeny.setObjectName("menuMeny")
        RF_Entry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RF_Entry)
        self.statusbar.setObjectName("statusbar")
        RF_Entry.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(RF_Entry)
        self.toolBar.setObjectName("toolBar")
        RF_Entry.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(RF_Entry)
        self.toolBar_2.setObjectName("toolBar_2")
        RF_Entry.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionExport_CSV = QtWidgets.QAction(RF_Entry)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionSettings = QtWidgets.QAction(RF_Entry)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(RF_Entry)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMeny.addAction(self.actionExport_CSV)
        self.menuMeny.addAction(self.actionSettings)
        self.menuMeny.addSeparator()
        self.menuMeny.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMeny.menuAction())

        self.retranslateUi(RF_Entry)
        QtCore.QMetaObject.connectSlotsByName(RF_Entry)

    def retranslateUi(self, RF_Entry):
        _translate = QtCore.QCoreApplication.translate
        RF_Entry.setWindowTitle(_translate("RF_Entry", "RF Entry"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RF_Entry", "Grupp"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RF_Entry", "Betalt"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RF_Entry", "Namn"))
        self.pushButton_3.setText(_translate("RF_Entry", "Start"))
        self.pushButton.setText(_translate("RF_Entry", "Clear Log"))
        self.menuMeny.setTitle(_translate("RF_Entry", "Meny"))
        self.toolBar.setWindowTitle(_translate("RF_Entry", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("RF_Entry", "toolBar_2"))
        self.actionExport_CSV.setText(_translate("RF_Entry", "Export CSV"))
        self.actionSettings.setText(_translate("RF_Entry", "Settings"))
        self.actionQuit.setText(_translate("RF_Entry", "Quit"))
